---
- name: Converge
  hosts: all
  vars:
    config_nested_virtualization: false
    upgrade_proxmox_os_packages: false
  tasks:
    - name: "Include proxmox-config"
      include_role:
        name: "proxmox-config"
