---
- name: Converge
  hosts: all
  vars:
    config_nested_virtualization: false
    upgrade_proxmox_os_packages: false
    dark_theme_install: false
    pci_trigger_update_refresh: false

    proxmox_packages:
      - vim
      - tmux
      - parted
      - curl
      - tcpdump

    install_dark_theme: false
  tasks:
    - name: remove apt repo in docker
      file:
        path: /etc/apt/sources.list.d/pve-install-repo.list
        state: absent

    - name: "Include proxmox-config"
      include_role:
        name: "proxmox-config"
