---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: proxmox-instance
    image: "spikebyte/docker-${MOLECULE_DISTRO:-proxmox7}-ansible:${MOLECULE_TAG:-latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
